name: Build
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
      - support/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ci